# Generated by Django 3.0.8 on 2020-11-29 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.CharField(max_length=255)),
                ('latlong', models.CharField(max_length=255)),
                ('noun', models.CharField(max_length=10)),
                ('verb', models.CharField(max_length=10)),
                ('timespent', models.IntegerField(null=True)),
                ('marked', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'event',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(max_length=255)),
                ('mode', models.CharField(max_length=255)),
                ('merchantid', models.IntegerField(default=0)),
                ('value', models.FloatField(default=0)),
                ('eventid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cube.Event')),
            ],
            options={
                'db_table': 'payment',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('eventid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cube.Event')),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cube.User'),
        ),
    ]
