# Generated by Django 3.0.8 on 2020-11-26 11:00

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('userid', models.IntegerField(primary_key=True, serialize=False)),
                ('ts', models.CharField(max_length=255)),
                ('latlong', models.CharField(max_length=255)),
                ('noun', models.CharField(max_length=10)),
                ('verb', models.CharField(max_length=10)),
                ('timespent', models.IntegerField(null=True)),
                ('properties', jsonfield.fields.JSONField(default=dict)),
            ],
            options={
                'db_table': 'event',
            },
        ),
    ]
