# Generated by Django 3.0.8 on 2020-11-28 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cube', '0002_auto_20201126_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='properties',
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(max_length=255)),
                ('mode', models.CharField(max_length=255)),
                ('merchantid', models.IntegerField(default=0)),
                ('value', models.IntegerField(default=0)),
                ('eventid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cube.Event')),
            ],
            options={
                'db_table': 'payment',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('eventid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cube.Event')),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
    ]
