# Generated by Django 3.0.8 on 2020-11-28 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cube', '0003_auto_20201128_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='value',
            field=models.FloatField(default=0),
        ),
    ]
