# Generated by Django 3.0.8 on 2020-11-29 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cube', '0004_auto_20201128_0319'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='marked',
            field=models.BooleanField(default=False),
        ),
    ]
